apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: v1
kind: Secret
metadata:
  name: secretblog
  namespace: blog
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASS: YWRtaW4xMjM0NQ==
  DB_HOST: a3ViZXJkcy5jMzJyeHpkZWs3bWcuYXAtc291dGhlYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  DB_NAME: YmxvZw==
